controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\User;
use app\models\forms\SignupForm;
use app\models\forms\LoginForm;
use app\models\forms\PasswordResetRequestForm;
use app\models\forms\ResetPasswordForm;

class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return string|\yii\web\Response the login form or a redirect response
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @return \yii\web\Response a redirect response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * @return string|\yii\web\Response the signup form, the signup message or
     * a redirect response
     */
    public function actionSignup()
    {
        if (Yii::$app->session->hasFlash('user-signed-up')) {
            return $this->render('signed-up');
        }

        $model = new SignupForm;
        if ($model->load(Yii::$app->request->post()) && $model->signup() !== null) {
            Yii::$app->session->setFlash('user-signed-up');
            return $this->refresh();
        } else {
            return $this->render('signup', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @return string|\yii\web\Response the confirmation failure message or a
     * redirect response
     */
    public function actionConfirmEmail($token)
    {
        if (Yii::$app->session->hasFlash('user-confirmed-email')) {
            return $this->render('confirmed-email');
        }

        $user = User::find()
            ->emailConfirmationToken($token)
            ->one();

        if ($user !== null && $user->confirmEmail()) {
            Yii::$app->session->setFlash('user-confirmed-email');
            return $this->refresh();
        } else {
            return $this->render('email-confirmation-failed');
        }
    }

    /**
     * @return string|\yii\web\Response the form to request a password reset or
     * a redirect response
     */
    public function actionRequestPasswordReset()
    {
        if (Yii::$app->session->hasFlash('user-requested-password-reset')) {
            return $this->render('requested-password-reset');
        }

        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->sendEmail()) {
            Yii::$app->session->setFlash('user-requested-password-reset');
            return $this->refresh();
        } else {
            return $this->render('request-password-reset', [
                'model' => $model,
            ]);
        }
    }

    /**
     * @return string|\yii\web\Response the form to reset the password or a
     * redirect response
     */
    public function actionResetPassword($token)
    {
        if (Yii::$app->session->hasFlash('user-password-was-reset')) {
            return $this->render('password-was-reset');
        }

        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->resetPassword()) {
            Yii::$app->session->setFlash('user-password-was-reset');
            return $this->refresh();
        }

        return $this->render('reset-password', [
            'model' => $model,
        ]);
    }

}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/* @var \yii\web\View $this */
/* @var string $content */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'My Company',
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            $menuItems = [
                ['label' => 'Home', 'url' => ['/site/index']],
            ];
            if (Yii::$app->user->isGuest) {
                $menuItems[] = ['label' => 'Signup', 'url' => ['/user/signup']];
                $menuItems[] = ['label' => 'Login', 'url' => ['/user/login']];
            } else {
                $menuItems[] = [
                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                    'url' => ['/user/logout'],
                    'linkOptions' => ['data-method' => 'post']
                ];
            }
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => $menuItems,
            ]);
            NavBar::end();
        ?>

        <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>
        <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>